
name: Install Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  install-test:
    runs-on: ubuntu-slim
    if: >
      github.event_name == 'workflow_dispatch' ||
      contains(github.event.head_commit.message, '[install]') ||
      contains(github.event.pull_request.title, '[install]')

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: stable

      - name: Install dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y git nodejs npm ripgrep
          sudo apt-get install -y fd-find
          sudo ln -sf /usr/bin/fdfind /usr/local/bin/fd

      - name: Install test
        run: make test-install NVIM_TEST_DIR=/tmp/nvim-test

      - name: Functional test
        run: make test-functional NVIM_TEST_DIR=/tmp/nvim-test
