
name: Tests macros

on:
  push:
    branches: [ "main" ]

  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip GA')"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run tests
        uses: addnab/docker-run-action@v3
        with:
          image: ghcr.io/fedemengo/fennel:1.3.0
          options: --platform linux/amd64 -v ${{ github.workspace }}:/nvim --entrypoint sh
          run: |
            cd /nvim/
            ./scripts/test.sh


